### ISSUE TITLE
Properties of yum_repository resource need to be configurable

### ISSUE THREAD

**Issue by haidangwa** [chef-cookbooks/chef-yum-docker#2]
### Cookbook version
2.0.0

### Chef-client version
12.11.1

### Platform Details
rhel6 and rhel7

### Scenario:
We would like to use wrap this cookbook, but be able to point the yum repository at another repo URL, such as our internal Nexus repo that proxies and caches the docker repo for our nodes that cannot exit their datacenters. Similar functionality in the yum-docker cookbook, which we are currently wrapping and using (https://supermarket.chef.io/cookbooks/yum-docker)

### Expected Result:
yum config that points at any repo URL and gpg key that we require, such as our internal Nexus repo.

### Actual Result:
The properties of the yum_repository are hardcoded and cannot be easily changed without using something like `edit_resource` in chef 12.10+

**Comment by tas50** [comment]
@haidangwa I'd welcome a PR to fix this

**Comment by tas50** [comment]
This will be released soon
