### ISSUE TITLE
typo in metadata

### ISSUE THREAD

**Issue by haidangwa** [chef-cookbooks/chef-yum-docker#3]
### Cookbook version
2.0.0

https://github.com/chef-cookbooks/chef-yum-docker/blob/master/metadata.rb#L9 appears to have a typo in the description for the default recipe.

### Expected Result:
The description should read `recipe 'chef-yum-docker::default', 'Sets up the Docker yum repository.'`

### Actual Result:
`recipe 'chef-yum-docker::default', 'Sets up the Docker apt repository.'`

**Comment by tas50** [comment]
Fixed. Thanks
