### ISSUE TITLE
Docker repo url/key change

### ISSUE THREAD

**Issue by rmoriz** [chef-cookbooks/chef-yum-docker#5]
With the introduction of CE and CC they moved away from dockerproject.org to docker.com.

See:

https://docs.docker.com/engine/installation/linux/docker-ce/centos/
https://docs.docker.com/engine/installation/linux/docker-ee/centos/

https://github.com/chef-cookbooks/docker/issues/891

gpg key also changed.

**Comment by rmoriz** [comment]
To make everything more complex, https://download.docker.com/linux/centos/7/x86_64/stable/Packages/ serves only new released and https://yum.dockerproject.org/repo/main/centos/7/Packages/ seems only to carry versions up to 17.05

**Comment by chasebolt** [comment]
The current repo we have pinned eventually will get 17.06 - it is just
slow. What I don't know is why the new repo skipped 17.05. Will have to
research on why that is to get a better understanding of their repos.

**Comment by rmoriz** [comment]
*"Starting with Docker 17.03, Docker uses a time-based release schedule, outlined below."*
https://docs.docker.com/engine/installation/#time-based-release-schedule

So download.docker.com will only have the "stable" releases every three months and https://yum.dockerproject.org/ has the monthly "edge" releases but **not** the "stable" ones. 

*"For that reason, on Linux distributions, you need to enable both channels."*

🙈

**Comment by tas50** [comment]
Makes perfect sense...

**Comment by rmoriz** [comment]
This also affects the https://github.com/chef-cookbooks/chef-apt-docker cookbook, however maybe just a README fix to tell the users to provide the attributes of choice for either of the repos

**Comment by tas50** [comment]
Closing this out since we shipped the fix
