### ISSUE TITLE
Flag to enable only stable repo ?

### ISSUE THREAD

**Issue by dushyant28** [chef-cookbooks/chef-yum-docker#9]
### Cookbook version
Latest

### Chef-client version
13.6

### Platform Details
Centos 7.4

### Scenario:
I need only the stable repo. So that i use only the stable version the package in prod.

**Comment by tas50** [comment]
Out of the box we lay down all 3 repos, but only enable the stable repo. Also this cookbook is no longer used with the latest version of the Docker cookbook.
